AWSTemplateFormatVersion: '2010-09-09'
Description: CLOUDACADEMY - Creates new CodeBuild and ECR build environment
Parameters:
  ECRRepoName:
    Description: Name of the ECR repo
    Default: frauddetectrepo
    Type: String
  FraudDetectImageTagName:
    Description: ECR Tag Name applied to Fraud Detection docker image
    Default: frauddetect
    Type: String    
Resources:
  MyRepository:
    DependsOn: FraudDetectCodeBuildEC2ClusterInstanceRole 
    Type: "AWS::ECR::Repository"
    Properties: 
      RepositoryName: !Ref ECRRepoName
      RepositoryPolicyText:
        Version: '2008-10-17'
        Statement:
        - Sid: AllowPushPull
          Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:role/FraudDetectCodeBuildEC2ClusterInstanceRole
          Action:
          - ecr:GetDownloadUrlForLayer
          - ecr:BatchGetImage
          - ecr:BatchCheckLayerAvailability
          - ecr:PutImage
          - ecr:InitiateLayerUpload
          - ecr:UploadLayerPart
          - ecr:CompleteLayerUpload
  MLBuildImageProject:
    Type: AWS::CodeBuild::Project
    DependsOn: FraudDetectCodeBuildRole
    Properties:
      Name: FraudDetectionBuildProject
      Description: Builds ML Image and uploads to ECR
      ServiceRole: !Ref FraudDetectCodeBuildRole
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:1.12.1
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: !Sub ${AWS::AccountId}
          - Name: AWS_REG
            Value: !Sub ${AWS::Region}            
          - Name: IMAGE_REPO_NAME
            Value: !Ref ECRRepoName
          - Name: IMAGE_TAG
            Value: !Ref FraudDetectImageTagName
      Source:
        Location: arn:aws:s3:::codebuild-frauddetect/code.zip
        Type: S3
      TimeoutInMinutes: 10
      Tags:
        - Key: Key1
          Value: Value1
        - Key: Key2
          Value: Value2

  FraudDetectCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: FraudDetectCodeBuildRole2 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: FraudDetectCodeBuildPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: [
              'ecr:*'
            ]
            Resource: '*'
          - Effect: Allow
            Action: [
              'logs:CreateLogGroup',
              'logs:CreateLogStream',
              'logs:PutLogEvents'
            ]
            Resource: [
              !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/FraudDetectionBuildProject',
              !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/FraudDetectionBuildProject:*'
            ]
          - Effect: Allow
            Action: [
              's3:PutObject',
              's3:GetObject',
              's3:GetObjectVersion'
            ]
            Resource: !Sub 'arn:aws:s3:::codepipeline-${AWS::Region}-*'

  FraudDetectCodeBuildEC2ClusterInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: FraudDetectCodeBuildEC2ClusterInstanceRole 
      AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: ecs-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: [
              'ecr:GetAuthorizationToken',
              'ecs:CreateCluster', 
              'ecs:DeregisterContainerInstance', 
              'ecs:DiscoverPollEndpoint',
              'ecs:Poll', 
              'ecs:RegisterContainerInstance', 
              'ecs:StartTelemetrySession',
              'ecs:Submit*', 
              'logs:CreateLogStream', 
              'logs:PutLogEvents'
            ]
            Resource: '*'