version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region eu-west-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ca-container-registry:frauddetection .
      - docker tag ca-container-registry:frauddetection 331058736108.dkr.ecr.eu-west-1.amazonaws.com/ca-container-registry:frauddetection
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 331058736108.dkr.ecr.eu-west-1.amazonaws.com/ca-container-registry:frauddetection
